IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Cliente')
BEGIN
	CREATE TABLE Cliente(
		Id INT NOT NULL IDENTITY(1,1) UNIQUE CLUSTERED,
		Nome VARCHAR(30) NOT NULL,
		Cpf VARCHAR(11) NOT NULL,
		DataNascimento DATETIME NOT NULL,
		Logradouro VARCHAR(30) NOT NULL,
		Bairro VARCHAR(30) NOT NULL,
		Cidade VARCHAR(30) NOT NULL,
		Uf VARCHAR(2) NOT NULL,
	CONSTRAINT [PK_Id_Cliente] PRIMARY KEY ([Id] ASC))
END